language: node.js
node_js:
  - 10

before_install:
  - npm install -g @angular/cli
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0

install: npm install

branches:
  only:
  - master

deploy:
  skip_cleanup: true
  provider: heroku
  app: tv-days
  api_key:
    secure: 09173705-3ce1-436d-9adc-397f17148dcf
